kumuluzee:
  name: ${artifactId}
  version: ${version}
  dev:
    scan-libraries:
      - ${artifactId}-lib
      - rest-lib
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count, Content-Type"
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    ui:
      mapping: /openapi/ui
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/${artifactId}-db
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/${artifactId}-db
      connection-url: jdbc:postgresql://localhost:5432/${artifactId}
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      changelogs:
        - jndi-name: jdbc/${artifactId}-db
          file: db/db.changelog-master.xml
          startup:
            drop-all: false
            update: true